import { NextResponse } from "next/server";

import { getUserOr401 } from "@/lib/api-helpers";
import { getOrCreateDefaultBoard } from "@/server/db/boards";
import { listByBoard } from "@/server/db/cards";

export async function GET() {
  const user = await getUserOr401();
  if (!(user as any).id) return user as unknown as NextResponse;

  const boardRes = await getOrCreateDefaultBoard((user as any).id);
  if (!boardRes.ok) {
    return NextResponse.json({ message: "Failed to resolve board" }, { status: 500 });
  }
  const board = boardRes.value;

  // Load tasks for the board
  const raw = await listByBoard(board.id);
  const tasks = raw.map(t => ({
    id: t.id,
    title: t.title,
    descriptionMarkdown: t.descriptionMarkdown,
    columnId: t.columnId,
    priority: t.priority,
    estimatedPomodoros: t.estimatedPomodoros ?? null,
    autoGenerated: t.autoGenerated,
    createdAt: t.createdAt.toISOString(),
  }));

  // Normalize board for UI: columns map + columnOrder + tasks map
  const columnOrder = board.columns
    .slice()
    .sort((a, b) => a.position - b.position)
    .map(c => c.id);

  const columnsMap = Object.fromEntries(
    board.columns.map(c => [c.id, { id: c.id, name: c.name, position: c.position, taskIds: [] as string[] }]),
  );

  for (const t of tasks) {
    const col = columnsMap[t.columnId];
    if (col) col.taskIds.push(t.id);
  }

  const tasksMap = Object.fromEntries(tasks.map(t => [t.id, t]));

  return NextResponse.json({
    board: {
      id: board.id,
      title: board.title,
      columnOrder,
      columns: columnsMap,
      tasks: tasksMap,
    },
  });
}
