import { NextResponse } from "next/server";

import { prisma } from "@/lib/prisma";
import { getOrCreateDbUser } from "@/lib/get-or-create-user";
import { getOrCreateDefaultBoard } from "@/lib/board";

export async function GET() {
  const user = await getOrCreateDbUser();
  if (!user) {
    return NextResponse.json({ message: "Unauthorized" }, { status: 401 });
  }

  const board = await getOrCreateDefaultBoard(user.id);

  // Load tasks for the board
  const tasks = await prisma.task.findMany({
    where: { boardId: board.id },
    orderBy: { createdAt: "asc" },
    select: {
      id: true,
      title: true,
      descriptionMarkdown: true,
      columnId: true,
      priority: true,
      estimatedPomodoros: true,
      autoGenerated: true,
      createdAt: true,
    },
  });

  // Normalize board for UI: columns map + columnOrder + tasks map
  const columnOrder = board.columns
    .slice()
    .sort((a, b) => a.position - b.position)
    .map(c => c.id);

  const columnsMap = Object.fromEntries(
    board.columns.map(c => [c.id, { id: c.id, name: c.name, position: c.position, taskIds: [] as string[] }]),
  );

  for (const t of tasks) {
    const col = columnsMap[t.columnId];
    if (col) col.taskIds.push(t.id);
  }

  const tasksMap = Object.fromEntries(tasks.map(t => [t.id, t]));

  return NextResponse.json({
    board: {
      id: board.id,
      title: board.title,
      columnOrder,
      columns: columnsMap,
      tasks: tasksMap,
    },
  });
}
