import { NextResponse } from "next/server";
import { getUserOr401, readJson, jsonError } from "@/lib/api-helpers";
import { prisma } from "@/lib/prisma";
import { getOrCreateDefaultBoard } from "@/lib/board";

type TaskDTO = {
  title: string;
  descriptionMarkdown?: string;
  priority?: "LOW" | "MEDIUM" | "HIGH";
  tags?: string[];
  estimatedPomodoros?: number | null;
};

export async function POST(req: Request) {
  const user = await getUserOr401();
  if (!(user as any).id) return user as unknown as NextResponse;

  const body = await readJson<{ tasks?: TaskDTO[] }>(req);
  const tasks = (body?.tasks ?? []) as TaskDTO[];
  if (!Array.isArray(tasks) || tasks.length === 0) {
    return NextResponse.json({ created: 0 });
  }

  const board = await getOrCreateDefaultBoard((user as any).id);
  const todoColumn = board.columns.find((c) => c.name.toLowerCase().includes("todo")) ?? board.columns[0];

  const data = tasks.map((t) => ({
    boardId: board.id,
    columnId: todoColumn.id,
    title: t.title,
    descriptionMarkdown: t.descriptionMarkdown ?? "",
    priority: t.priority ?? "MEDIUM",
    status: "TODO" as const,
    tags: t.tags ?? [],
    estimatedPomodoros: t.estimatedPomodoros ?? null,
    autoGenerated: true,
    aiPlanned: true,
    fromBrainDump: true,
    source: "orchestrator",
  }));

  const result = await prisma.task.createMany({ data });
  return NextResponse.json({ created: result.count });
}
