import { PageShell } from "@/components/layout/page-shell";
export const dynamic = 'force-dynamic';

async function fetchWeekly() {
  const base = process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000';
  const res = await fetch(`${base}/api/reports/weekly/list`, { cache: 'no-store' });
  return res.json().catch(() => ({ items: [] })) as Promise<{ items: { id: string; createdAt: string; summary: string; highlights?: string[]; sentiment?: string }[] }>;
}

export default async function ReportsPage() {
  const { items } = await fetchWeekly();
  return (
    <PageShell>
      <div className="mb-6">
        <h1 className="text-2xl font-semibold">Reports</h1>
        <p className="text-sm text-muted-foreground">Weekly summaries generated by the agent.</p>
      </div>
      <div className="space-y-4">
        {items.length === 0 ? (
          <div className="text-sm text-muted-foreground">No reports yet.</div>
        ) : (
          items.map((it) => (
            <div key={it.id} className="rounded-xl border bg-card p-4">
              <div className="flex items-center justify-between">
                <div className="text-sm font-medium">{new Date(it.createdAt).toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' })}</div>
                {it.sentiment && <div className="text-xs text-muted-foreground">{it.sentiment}</div>}
              </div>
              <p className="mt-2 text-sm">{it.summary}</p>
              {Array.isArray(it.highlights) && it.highlights.length > 0 && (
                <ul className="mt-3 list-disc pl-5 text-sm text-muted-foreground space-y-1">
                  {it.highlights.slice(0, 5).map((h, i) => <li key={i}>{h}</li>)}
                </ul>
              )}
            </div>
          ))
        )}
      </div>
    </PageShell>
  );
}
