import { PageShell } from "@/components/layout/page-shell";
export const dynamic = 'force-dynamic';

async function fetchWeekly() {
  try {
    const res = await fetch(`/api/reports/weekly/list`, { cache: 'no-store' });
    if (!res.ok) return { items: [] } as any;
    const data = await res.json().catch(() => ({ items: [] }));
    if (!data || !Array.isArray(data.items)) return { items: [] } as any;
    return data as { items: { id: string; createdAt: string; summary: string; highlights?: string[]; sentiment?: string }[] };
  } catch {
    return { items: [] } as any;
  }
}

export default async function ReportsPage() {
  const data = await fetchWeekly();
  const items = Array.isArray((data as any)?.items) ? (data as any).items : [];
  return (
    <PageShell>
      <div className="mb-6">
        <h1 className="text-2xl font-semibold">Reports</h1>
        <p className="text-sm text-muted-foreground">Weekly summaries generated by the agent.</p>
      </div>
      <div className="space-y-4">
        {items.length === 0 ? (
          <div className="text-sm text-muted-foreground">No reports yet.</div>
        ) : (
          items.map((it) => (
            <div key={it.id} className="rounded-xl border bg-card p-4">
              <div className="flex items-center justify-between">
                <div className="text-sm font-medium">{new Date(it.createdAt).toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' })}</div>
                {it.sentiment && <div className="text-xs text-muted-foreground">{it.sentiment}</div>}
              </div>
              <p className="mt-2 text-sm">{it.summary}</p>
              {Array.isArray(it.highlights) && it.highlights.length > 0 && (
                <ul className="mt-3 list-disc pl-5 text-sm text-muted-foreground space-y-1">
                  {it.highlights.slice(0, 5).map((h, i) => <li key={i}>{h}</li>)}
                </ul>
              )}
            </div>
          ))
        )}
      </div>
    </PageShell>
  );
}
