// Lightweight DTOs used by the AI layer. You can switch these
// to Prisma types later when persisting.

export type TaskPriority = "LOW" | "MEDIUM" | "HIGH";
export type TaskStatus = "BACKLOG" | "TODO" | "IN_PROGRESS" | "DONE" | "ARCHIVED";
export type TaskKind = "DEEP" | "SHALLOW";

export interface TaskDTO {
  id?: string;
  boardId?: string;
  columnId?: string;
  title: string;
  descriptionMarkdown?: string;
  priority?: TaskPriority;
  status?: TaskStatus;
  estimatedPomodoros?: number | null;
  tags?: string[];
  autoGenerated?: boolean;
  // Classification
  kind?: TaskKind; // DEEP vs SHALLOW (binary)
  depthScore?: number; // 0..1 (higher = deeper work)
}

export interface GemAward {
  slug: string; // e.g., "obsidian-focus"
  title: string;
  oneLineLore: string;
  imageUrl: string;
  relatedTaskIds: string[];
}

export interface FlashcardDTO {
  id?: string;
  question: string;
  answer: string;
  noteId?: string;
}

export interface QuizQuestionDTO {
  type: "MCQ" | "SHORT_ANSWER";
  promptMarkdown: string;
  options?: string[];
  correctAnswer?: string;
}

export interface AgentContext {
  userId: string;

  // Raw input from UI
  brainDumpText?: string;
  quickTodoText?: string;
  noteMarkdown?: string;
  boardId?: string;

  // Outputs from earlier agents
  generatedTasks?: TaskDTO[];
  enrichedTasks?: TaskDTO[];
  flashcards?: FlashcardDTO[];
  quizQuestions?: QuizQuestionDTO[];
  gemAwards?: GemAward[];
  gamifyResult?: {
    shards: any[];
    awards: string[];
    flavorText?: string;
    xpDelta?: number;
    streakAfter?: number;
  };

  // Misc
  gamification?: {
    action: "TASK_COMPLETE" | "POMODORO_COMPLETE";
    taskId?: string;
    sessionId?: string;
    [key: string]: any;
  };
  meta?: Record<string, unknown>;
}

export interface AgentResult {
  context: AgentContext;
  debug?: any;
}

export interface Agent {
  name: string;
  description: string;
  run(ctx: AgentContext): Promise<AgentResult>;
}
