import { NextRequest, NextResponse } from "next/server";
import { enricherAgent } from "@/lib/ai/agents/enricherAgent";
import { z } from "zod";

const BodySchema = z.object({
    taskId: z.string().optional(),
    taskTitle: z.string().optional(),
    taskDescription: z.string().optional(),
});

export async function POST(req: NextRequest) {
    try {
        const body = await req.json();
        const { taskId, taskTitle, taskDescription } = BodySchema.parse(body);

        // Mock context for the agent
        const ctx: any = {
            userId: "debug-user",
            generatedTasks: taskId ? [] : [{
                id: "temp-id",
                title: taskTitle || "Untitled",
                descriptionMarkdown: taskDescription || "",
                status: "TODO",
                priority: "MEDIUM",
                tags: [],
                autoGenerated: true,
            }],
        };

        // If we had a real task ID, we'd fetch it here, but for debug we might just simulate or rely on the agent's logic
        // The enricher agent currently expects `generatedTasks` in context or looks up tasks.
        // Let's assume we are testing the "enrichment" logic.

        const result = await enricherAgent.run({ ...ctx, context: ctx });

        return NextResponse.json(result);
    } catch (error) {
        console.error("[API] Enricher agent failed", error);
        return NextResponse.json(
            { error: "Failed to run enricher agent", details: String(error) },
            { status: 500 }
        );
    }
}
